/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/clientes': RouteRecordInfo<'/admin/clientes', '/admin/clientes', Record<never, never>, Record<never, never>>,
    '/admin/configuracion': RouteRecordInfo<'/admin/configuracion', '/admin/configuracion', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/pedidos': RouteRecordInfo<'/admin/pedidos', '/admin/pedidos', Record<never, never>, Record<never, never>>,
    '/admin/product': RouteRecordInfo<'/admin/product', '/admin/product', Record<never, never>, Record<never, never>>,
    '/admin/stock': RouteRecordInfo<'/admin/stock', '/admin/stock', Record<never, never>, Record<never, never>>,
    '/auth/confirm-account': RouteRecordInfo<'/auth/confirm-account', '/auth/confirm-account', Record<never, never>, Record<never, never>>,
    '/auth/confirm-email': RouteRecordInfo<'/auth/confirm-email', '/auth/confirm-email', Record<never, never>, Record<never, never>>,
    '/confirm-account': RouteRecordInfo<'/confirm-account', '/confirm-account', Record<never, never>, Record<never, never>>,
    '/confirm-email': RouteRecordInfo<'/confirm-email', '/confirm-email', Record<never, never>, Record<never, never>>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/verify-email': RouteRecordInfo<'/verify-email', '/verify-email', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/clientes.vue': {
      routes: '/admin/clientes'
      views: never
    }
    'src/pages/admin/configuracion.vue': {
      routes: '/admin/configuracion'
      views: never
    }
    'src/pages/admin/dashboard.vue': {
      routes: '/admin/dashboard'
      views: never
    }
    'src/pages/admin/pedidos.vue': {
      routes: '/admin/pedidos'
      views: never
    }
    'src/pages/admin/product.vue': {
      routes: '/admin/product'
      views: never
    }
    'src/pages/admin/stock.vue': {
      routes: '/admin/stock'
      views: never
    }
    'src/pages/auth/confirm-account.vue': {
      routes: '/auth/confirm-account'
      views: never
    }
    'src/pages/auth/confirm-email.vue': {
      routes: '/auth/confirm-email'
      views: never
    }
    'src/pages/confirm-account.vue': {
      routes: '/confirm-account'
      views: never
    }
    'src/pages/confirm-email.vue': {
      routes: '/confirm-email'
      views: never
    }
    'src/pages/forgot-password.vue': {
      routes: '/forgot-password'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/products.vue': {
      routes: '/products'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/reset-password.vue': {
      routes: '/reset-password'
      views: never
    }
    'src/pages/verify-email.vue': {
      routes: '/verify-email'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
